# Generated by Django 4.2.7 on 2026-01-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
    ]
