# Generated by Django 4.2.7 on 2026-01-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_answer_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
    ]
